/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
//import controller.Koneksi;
import Controller.Cucian_Controller;
import Controller.Transaksi;
import Model.*;
import database.Koneksi;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.*;
import java.awt.print.*;
import javafx.print.Printer; 
import javax.swing.JTextArea;

/**
 *
 * @author ACER
 */
public class TransaksiPembayaran extends javax.swing.JFrame {
    private Transaksi transaksi;
    private ArrayList<Transaksi_pembayaran> arrPembayaran;
    private ArrayList<TransaksiCucian> arrCucian;
    private Cucian_Controller cuciancon;
    private Koneksi koneksi;
    Integer Harga_Total, kembali2;
    
    /**
     * Creates new form TransaksiKeluar
     */
    public TransaksiPembayaran() throws SQLException {
        initComponents();
        this.arrPembayaran = new ArrayList<>();
        this.arrCucian = new ArrayList<>();
        this.cuciancon = new Cucian_Controller();
        this.transaksi = new Transaksi();
        this.koneksi = new Koneksi();
        this.Harga_Total = 0;
        this.kembali2 = 0;
        this.showTabelPembayaran();
        this.showTabelCucian();
        this.showComboBoxCucian();
    }

    public void showTabelPembayaran() throws SQLException {
        DefaultTableModel dtmBayar = new DefaultTableModel(new String[]
        {"ID Pembayaran", "Berat Cucian", "Harga Total", "Tunai", "Kembalian", "Status"}, 0);
        dtmBayar.setRowCount(0);

        for (Transaksi_pembayaran tp : this.transaksi.getDataPembayaran()) {
            dtmBayar.addRow(new String[]{tp.getId_Pembayaran().toString(), tp.getTransaksi_cucian().getBerat().toString(),tp.getHarga_Total().toString(),
                tp.getTunai().toString(), tp.getKembalian().toString(), tp.getStatus()});
        }

        this.tblKeluar.setModel(dtmBayar);
    }
    
    public void showTabelCucian() throws SQLException{
        DefaultTableModel model = new DefaultTableModel();
        model.setRowCount(0);
        model.addColumn("ID TRANSAKSI");
        model.addColumn("NAMA PELANGGAN");
        model.addColumn("JENIS CUCIAN");
        model.addColumn("HARGA JENIS CUCIAN");
        model.addColumn("BERAT CUCIAN");
        
        String kodeSql = "SELECT * FROM Data_cucian ORDER BY Id_transaksi ASC";
        ResultSet res = this.koneksi.GetData(kodeSql);
        while (res.next()) {
                model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5)});
            }
        datacucian.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        HargaTotal = new javax.swing.JTextField();
        print = new javax.swing.JButton();
        Tunai = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Kembalian = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        datacucian = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblKeluar = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        kuitansi = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        cbIdtransaksi = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        berat = new javax.swing.JTextField();
        Hitung = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        hrg = new javax.swing.JTextField();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel1.setText("Transaksi Pembayaran Cucian");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("ID Transaksi");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButton1.setText("Lunas");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jRadioButton2.setText("Belum Lunas");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Harga Total");

        HargaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaTotalActionPerformed(evt);
            }
        });
        HargaTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                HargaTotalKeyTyped(evt);
            }
        });

        print.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        Tunai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TunaiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Tunai");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Kembalian");

        datacucian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        datacucian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datacucianMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(datacucian);

        tblKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblKeluar);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setText("Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        kuitansi.setColumns(20);
        kuitansi.setRows(5);
        jScrollPane4.setViewportView(kuitansi);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setText("Struct");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cbIdtransaksi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Berat Cucian");

        Hitung.setText("Hitung");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("Harga Cucian");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Hitung)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbIdtransaksi, 0, 82, Short.MAX_VALUE)
                                        .addComponent(berat)
                                        .addComponent(hrg))
                                    .addComponent(HargaTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tunai, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton2))
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(25, 25, 25)))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(print)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(340, 340, 340))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(Tunai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbIdtransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(berat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(hrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Hitung)))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(HargaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(print)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void kosong(){
        HargaTotal.setText("");
        Tunai.setText("");
        Kembalian.setText("");
    }
    
    private void showComboBoxCucian() throws SQLException {
        DefaultComboBoxModel dcbmpelanggan = new DefaultComboBoxModel();

        for (Transaksi_cucian dp : this.transaksi.getDataCucian()) {
            dcbmpelanggan.addElement(dp.getId_Transaksi());
        }
        this.cbIdtransaksi.setModel(dcbmpelanggan);
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            Transaksi_pembayaran tp = new Transaksi_pembayaran();
                try { 
                        tp.setTransaksi_cucian(this.transaksi.getDataCucian().get(this.cbIdtransaksi.getSelectedIndex()));
                        tp.setHarga_Total(Integer.parseInt(HargaTotal.getText()));
                        tp.setTunai(Integer.parseInt(Tunai.getText()));
                        tp.setKembalian(Integer.parseInt(Kembalian.getText()));
                         if(jRadioButton1.isSelected()){
                             tp.setStatus(jRadioButton1.getText());
                         }else if(jRadioButton2.isSelected()){
                             tp.setStatus(jRadioButton2.getText());
                         }else{
                            JOptionPane.showMessageDialog(null, "Tentukan Pilihan ");
                         }
                        this.showComboBoxCucian(); 
                        this.transaksi.getDataPembayaran();
                        this.transaksi.insertPembayaran(tp);
                        this.showTabelPembayaran();
                        kosong();
                } catch (SQLException ex) {
                    Logger.getLogger(Transaksi_cucian.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        
        try{
            
            kuitansi.print();
            
        }catch(java.awt.print.PrinterException e){
            System.err.format("No Printer Found", e.getMessage());
        }
        
    }//GEN-LAST:event_printActionPerformed

    private void datacucianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datacucianMouseClicked
        // TODO add your handling code here:
        int baris = datacucian.getSelectedRow();
        this.hrg.setText(datacucian.getValueAt(baris, 3).toString());
        this.berat.setText(datacucian.getValueAt(baris, 4).toString());
    }//GEN-LAST:event_datacucianMouseClicked

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1MouseClicked

    private void HargaTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HargaTotalKeyTyped
        // TODO add your handling code here: 
    }//GEN-LAST:event_HargaTotalKeyTyped

    private void HargaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaTotalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_HargaTotalActionPerformed

    private void TunaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TunaiActionPerformed
        // TODO add your handling code here:
        String tunai1 = Tunai.getText();
        String t = HargaTotal.getText();
        int value = Integer.parseInt(tunai1);
        int value2  = Integer.parseInt(t);
        int kembaliann = value-value2;
        Kembalian.setText(""+kembaliann);
                
                
    }//GEN-LAST:event_TunaiActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try { 
            Transaksi_pembayaran tp = this.transaksi.getDataPembayaran().get(this.tblKeluar.getSelectedRow());
            Transaksi_cucian tc = this.transaksi.getDataCucian().get(this.tblKeluar.getSelectedRow());
            Data_Pelanggan dp = this.transaksi.getDataPelanggan().get(this.tblKeluar.getSelectedRow());
                    String teks = "" + "=========================PELANGGAN=========================" + "\n"
                    + "Nama Pelanggan : " + tc.getDataPelanggan().getNama_Pelanggan()+ "\n"
                    + "No Telp : " + tc.getDataPelanggan().getNo_Tlp()+ "\n"
                    + "Alamat : " + tc.getDataPelanggan().getAlamat()+ "\n"
                    + "Jenis Cucian : " + dp.getJenisCucian().getNama_jenis_cucian()+ "\n"
                    + "Berat Cucian : " + tc.getBerat()+ "\n"
                    + "Harga Total : " + tp.getHarga_Total()  + "\n"
                    + "Tunai : " + tp.getTunai() + "\n"
                    + "Kembalian : " + tp.getKembalian() + "\n"
                    + " Status : " + tp.getStatus() + "\n"
                    + "==============================================================" + "\n";
                    this.kuitansi.setText(teks);
            } catch (SQLException ex) {
            Logger.getLogger(TransaksiPembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
                int brt = Integer.parseInt(berat.getText());
                int hrg2 = Integer.parseInt(hrg.getText());
                Harga_Total = brt*hrg2;
                showHargaTotal();
    }//GEN-LAST:event_HitungActionPerformed

    private void showHargaTotal(){
        this.HargaTotal.setText(String.valueOf(this.Harga_Total));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TransaksiPembayaran().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TransaksiPembayaran.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HargaTotal;
    private javax.swing.JButton Hitung;
    private javax.swing.JTextField Kembalian;
    private javax.swing.JTextField Tunai;
    private javax.swing.JTextField berat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbIdtransaksi;
    private javax.swing.JTable datacucian;
    private javax.swing.JTextField hrg;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea kuitansi;
    private javax.swing.JButton print;
    private javax.swing.JTable tblKeluar;
    // End of variables declaration//GEN-END:variables
}
